// <auto-generated />
using System;
using EasyStock.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyStock.API.Migrations.Auth
{
    [DbContext(typeof(AuthContext))]
    [Migration("20250701134715_AddRoleActually")]
    partial class AddRoleActually
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyStock.API.Models.UserAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BlDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LcUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAuths");
                });
#pragma warning restore 612, 618
        }
    }
}
